### ISSUE TITLE
Example code for Fig 7 in paper

### ISSUE THREAD

**Issue by sekocabas** [Columbia-Computational-X-Lab/DiffSMat#2]
Thank you for making the source code for your paper available. I was wondering if you could provide more examples demonstrating how different geometries can be used during an optimization run. For instance, is it possible for you to additionally share the code that generates the results in Fig 7 of the paper?

**Comment by 2iw31Zhv** [comment]
Hi Sekocabas,

Thanks for the issue!
I have attached an example [code](https://gist.github.com/2iw31Zhv/c6087267b471703a7da1aad9d86d607d) here to set up the experiment in Fig7 in the [paper](https://opg.optica.org/oe/fulltext.cfm?uri=oe-28-25-37773&id=444132###) 
You will need to write your own optimizer (like a simple gradient descent or L-BFGS-B) or find some interesting ones online as we have not released that part.

**Comment by sekocabas** [comment]
Thank you, I will take a look at the code you shared.
